
#see 03_organize_camels_macrosheds_nhm.R for download locations

source('src/global/camels_formatting_scripts/camels_helpers.R')
dir.create('scratch/camels_assembly/ms_attributes', recursive = TRUE, showWarnings = FALSE)

#root depth prep ####

root_depth_tib <- read_csv('data/general/camels_constants/root_depth_tib.csv',
                           show_col_types = FALSE)

all_vals <- tibble()
for(i in 1:nrow(root_depth_tib)){

    vals <- root_depth_tib[i, ]

    if(is.na(vals$a)) next

    all_tib = tibble(a = vals$a,
                     b = vals$b,
                     d = seq(0, vals$d, by = 0.001),
                     e = exp(1),
                     y = (0.5*(e^-(a*d) + e^-(b*d)))) %>%
        mutate(y = round(y, 3))

    # 10, 25, 50, 75, and 99

    mean_depth_50 <- quantile(all_tib$d, probs = c(.5))
    mean_depth_99 <- quantile(all_tib$d, probs = c(.99))

    fin <- tibble(id = vals$type,
                  mean_root_depth_50 = mean_depth_50,
                  mean_root_depth_99 = mean_depth_99)

    all_vals <- rbind(all_vals, fin)
}

write_csv(all_vals, 'scratch/camels_assembly/igbp_root_depth_means.csv')


#all attributes loop ####

for(i in 1:nrow(network_domain)){

    ntw <- pull(network_domain[i, 1])
    dmn <- pull(network_domain[i, 2])

    print(glue('working on {dmn} ({i} of {nrow(network_domain)})'))

    sites_ <- site_data %>%
        filter(domain == !!dmn,
               site_type == 'stream_gauge',
               in_workflow == 1) %>%
        mutate(area_sqkm = ws_area_ha / 100) %>%
        select(site_code, gauge_lat = latitude, gauge_lon = longitude, area_sqkm)

    dir.create(glue('scratch/camels_assembly/ms_attributes/{dmn}'),
               recursive = TRUE,
               showWarnings = FALSE)

    #### CLIMATE ####

    daymet <- try({
        read_csv(glue('scratch/camels_assembly/daymet_with_pet/{dmn}.csv'),
                 show_col_types = FALSE)
        # filter(date >= ymd('1989-10-01'),
        #        date <= ymd('2009-09-30'))
    }, silent = TRUE)

    if(! inherits(daymet, 'try-error')){

        sites <- unique(daymet$site_code)

        all_climate <- tibble()
        for(p in 1:length(sites)){

            one_site <- daymet %>%
                filter(site_code == !!sites[p]) %>%
                mutate(temp = (tmin + tmax) / 2) %>%
                mutate(pet = ifelse(pet < 0, 0, pet))
            # mutate(pet = ifelse(is.na(pet), 0, pet))

            one_site <- compute_clim_indices_camels(
                temp = one_site$temp, prec = one_site$prcp,
                pet = one_site$pet, day = one_site$date, tol = 0.1
            ) %>%
                mutate(site_code = !!sites[p])

            all_climate <- rbind(all_climate, one_site)
        }

        write_feather(all_climate, glue('scratch/camels_assembly/ms_attributes/{dmn}/clim.feather'))
    }

    #### VEGETATION ####

    # Landcover
    # Generated by general loop in data_acquisition
    modis_land_fils <- list.files(glue('data/{ntw}/{dmn}/ws_traits/modis_igbp/'),
                                  full.names = T)

    modis_landcover <- map_dfr(modis_land_fils, read_feather)

    if(nrow(modis_landcover)){

        landcover <- modis_landcover %>%
            # filter(year >= 2002 & year <= 2016) %>%
            group_by(site_code, var) %>%
            summarize(mean = mean(val, na.rm = TRUE),
                      .groups = 'drop') %>%
            mutate(var = sub('...', '', var))

        landcover_classes <- read_csv('data/general/camels_constants/modis_land_cover.csv',
                                      show_col_types = FALSE) %>%
            select(var = macrosheds_code, dom_land_cover = `IGBP name`, id = class_code)

        root_depth <- read_csv('scratch/camels_assembly/igbp_root_depth_means.csv',
                               show_col_types = FALSE)

        landcover_root <- left_join(landcover, landcover_classes, by = 'var') %>%
            left_join(root_depth, by = 'id') %>%
            mutate(mean = mean / 100) %>%
            mutate(root_depth_p_50 = mean * mean_root_depth_50,
                   root_depth_p_99 = mean * mean_root_depth_99) %>%
            group_by(site_code) %>%
            summarize(root_depth_50 = sum(root_depth_p_50, na.rm = TRUE),
                      root_depth_99 = sum(root_depth_p_99, na.rm = TRUE))

        landcover <- landcover %>%
            group_by(site_code) %>%
            filter(mean == max(mean, na.rm = TRUE)) %>%
            ungroup() %>%
            distinct(site_code, .keep_all = T)

        if(any(is.infinite(landcover$mean))) warning('inf landcover val in ', dmn)

        landcover_fin <- left_join(landcover, landcover_classes, by = 'var') %>%
            mutate(dom_land_cover_frac = mean / 100) %>%
            select(site_code, dom_land_cover_frac, dom_land_cover)

        all_veg <- left_join(landcover_fin, landcover_root, by = 'site_code')

        # Generated by general loop data_acquisition
        nlcd_fil <- list.files(glue('data/{ntw}/{dmn}/ws_traits/nlcd/'),
                               full.names = TRUE)

        if(length(nlcd_fil)){

            nlcd <- map_dfr(nlcd_fil, read_feather) %>%
                # filter(year == 2011) %>%
                filter(var %in% c('lg_nlcd_forest_dec', 'lg_nlcd_forest_evr', 'lg_nlcd_forest_mix')) %>%
                group_by(site_code) %>%
                summarize(frac_forest = sum(val) / 100,
                          .groups = 'drop')

            veg_fin <- left_join(nlcd, all_veg, by = 'site_code')
        } else {
            veg_fin <- all_veg
        }

        write_feather(veg_fin, glue('scratch/camels_assembly/ms_attributes/{dmn}/vege.feather'))
    }

    #### TERRAIN ####

    # Generated by general loop data_acquisition
    topo_fils <- list.files(glue('data/{ntw}/{dmn}/ws_traits/terrain/'),
                            full.name = T)

    if(length(topo_fils)){

        topo <- map_dfr(topo_fils, read_feather) %>%
            filter(var %in% c('te_slope_mean', 'te_elev_mean')) %>%
            pivot_wider(names_from = 'var', values_from = 'val') %>%
            select(site_code, elev_mean = te_elev_mean, slope_mean = te_slope_mean)

        topo_fin <- full_join(sites_, topo, by = 'site_code') %>%
            mutate(slope_mean = slope_mean * 10)

        write_feather(topo_fin, glue('scratch/camels_assembly/ms_attributes/{dmn}/topo.feather'))
    }

    #### GEOLOGY ####

    # Generated by general loop data_acquisition
    lith_fils <- list.files(glue('data/{ntw}/{dmn}/ws_traits/lithology/'),
                            full.names = TRUE)

    lith <- map_dfr(lith_fils, read_feather)

    if(nrow(lith)){

        sites <- unique(lith$site_code)

        all_tib <- tibble()
        for(p in 1:length(sites)){

            lith_sites <- lith %>%
                filter(site_code == !!sites[p]) %>%
                arrange(desc(val))

            largest_name <- str_split_fixed(pull(lith_sites[1, 2]), '_', n = Inf)[1, 4]
            largest_val <- pull(lith_sites[1, 3])

            second_name <- str_split_fixed(pull(lith_sites[2, 2]), '_', n = Inf)[1, 4]
            second_val <- pull(lith_sites[2, 3])

            all_tib <- tibble(site_code = sites[p],
                                name = c('geol_class_1st', 'geol_class_2nd'),
                                var = c(largest_name, second_name),
                                val = c(largest_val, second_val)) %>%
                bind_rows(all_tib)
        }

        lith_carb <- lith %>%
            filter(var == 'pn_geol_class_SC') %>%
            select(site_code, carbonate_rocks_frac = val) %>%
            mutate(carbonate_rocks_frac = carbonate_rocks_frac / 100)

        vars_ <- ms_vars %>%
            filter(variable_subtype == 'Lithology') %>%
            mutate(look = str_extract(variable_code, '[^_]+$'))

        # vars_['geo_name'] <- substr(vars_$variable_name, 16, vars_$n)
        vars_['geo_name'] <- str_extract(vars_$variable_name, '(?<=: ).*$')

        vars_ <- vars_ %>%
            select(var = look, geo_name)

        all_lith <- left_join(all_tib, vars_, by = 'var') %>%
            select(-var) %>%
            pivot_wider(names_from = 'name', values_from = c('val', 'geo_name')) %>%
            select(site_code, geol_1st_class = geo_name_geol_class_1st, glim_1st_class_frac = val_geol_class_1st,
                   geol_2nd_class = geo_name_geol_class_2nd, glim_2nd_class_frac = val_geol_class_2nd) %>%
            mutate(glim_1st_class_frac = glim_1st_class_frac / 100,
                   glim_2nd_class_frac = glim_2nd_class_frac / 100) %>%
            mutate(geol_2nd_class = ifelse(glim_2nd_class_frac == 0, NA, geol_2nd_class))

        # Generated by general loop data_acquisition
        glhymps_fils <- list.files(glue('data/{ntw}/{dmn}/ws_traits/glhymps/'),
                                   full.names = T)

        glhymps <- map_dfr(glhymps_fils, read_feather) %>%
            filter(var %in% c('pm_sub_surf_porosity_mean', 'pm_sub_surf_permeability_mean')) %>%
            pivot_wider(names_from = 'var', values_from = 'val') %>%
            select(site_code, geol_porosity = pm_sub_surf_porosity_mean,
                   geol_permeability = pm_sub_surf_permeability_mean)

        final_geol <- left_join(all_lith, lith_carb, by = 'site_code') %>%
            left_join(glhymps, by = 'site_code')

        write_feather(final_geol, glue('scratch/camels_assembly/ms_attributes/{dmn}/geol.feather'))
    }

    #### SOIL ####

    # Generated by general loop data_acquisition
    soil_fils <- list.files(glue('data/{ntw}/{dmn}/ws_traits/nrcs_soils/'),
                            full.names = T)

    if(length(soil_fils)){

        soil_fin <- map_dfr(soil_fils, read_feather) %>%
            select(-pctCellErr) %>%
            filter(var %in% c('pf_soil_org', 'pf_soil_sand', 'pf_soil_silt', 'pf_soil_clay')) %>%
            pivot_wider(names_from = 'var', values_from = 'val') %>%
            select(site_code, sand_frac = pf_soil_sand, silt_frac = pf_soil_silt, clay_frac = pf_soil_clay,
                   organic_frac = pf_soil_org)

        write_feather(soil_fin, glue('scratch/camels_assembly/ms_attributes/{dmn}/soil.feather'))
    }
}

# # Move daily climate data to dmn folder
# for(i in 1:nrow(network_domain)) {
#
#     ntw <- network_domain[i, 1]
#     dmn <- network_domain[i, 2]
#
#     climate_path <- glue('neon_camels_attr/data/{n}_{d}_climate_pet.feather',
#                          n = ntw,
#                          d = dmn)
#
#     new_path <- glue('scratch/camels_assembly/ms_attributes/{d}/daymet_full_climate.feather',
#                      n = ntw,
#                      d = dmn)
#
#     file.copy(climate_path, new_path)
# }

# dir.create('data/ms_in_camels_format/camels', showWarnings = FALSE)
# file.copy('neon_camels_attr/data/large/clim.feather', 'data/ms_in_camels_format/camels/clim.feather',
#           overwrite = TRUE)
# }
