

#### Climate ####
# Load in data
    # File generated by general loop in data_acquisition
neon_daymet <- try(read_feather(glue('../data_acquisition/data/{n}/{d}/ws_traits/daymet/domain_climate.feather',
                                 n = network,
                                 d = domain)),
                   silent  = T)
    # only uncomment if using old daymet data that was altered in old pipeline
    # mutate(srad = srad*11.57407)

if(inherits(neon_daymet, 'try-error')) stop()

conf <- jsonlite::fromJSON('../data_acquisition/config.json')

    # macrosheds site data sheet
neon_sites <- sm(googlesheets4::read_sheet(
    conf$site_data_gsheet,
    na = c('', 'NA'),
    col_types = 'ccccccccnnnnncccc')) %>%
    filter(domain == !!pull(domain),
           site_type == 'stream_gauge') %>%
    select(site_code, latitude, longitude)

    # Generated by general loop in data acquisition
elev_fils <- list.files(glue('../data_acquisition/data/{n}/{d}/ws_traits/terrain/',
                             n = network,
                             d = domain),
                        full.names = TRUE)

all_elv <- map_dfr(elev_fils, read_feather) %>%
    filter(var == 'te_elev_mean') %>%
    select(site_code, elev = val)

df <- left_join(neon_daymet, neon_sites, by = 'site_code') %>%
    left_join(., all_elv, by = 'site_code')


a_cof <- terra::rast('neon_camels_attr/data/large/alpha/aptt1_30s/aptt1')

    # ws_boundaries generated by data aquisition

ws_prodname <- list.files(glue('../data_acquisition/data/{n}/{d}/derived/',
                               n = network,
                               d = domain))

ws_prodname <- grep('ws_boundary', ws_prodname, value = T)

if(length(ws_prodname) >1){
    vals <- as.numeric(str_match(ws_prodname, '^ws_boundary__ms([0-9]{3})')[,2])

    max_val <- max(vals)

    val_nchar <- nchar(max_val)

    if(val_nchar == 1){ new_val <- paste0('00', max_val)}
    if(val_nchar == 2){ new_val <- paste0('0', max_val)}

    ws_prodname <- paste0('ws_boundary__ms', new_val)
}

neon_shapes_fils <- list.files(glue('../data_acquisition/data/{n}/{d}/derived/{p}/',
                                    n = network,
                                    d = domain,
                                    p = ws_prodname),
                               full.names = T)

neon_alpha <- tibble()
for(i in 1:length(neon_shapes_fils)) {

    neon_shp <- sf::st_read(neon_shapes_fils[i],
                            quiet  = TRUE,
                            drivers = 'ESRI Shapefile') %>%
        sf::st_transform(., sf::st_crs(a_cof)) %>%
        terra::vect(.)

    croped <- terra::crop(a_cof, neon_shp)
    maksed <- terra::mask(croped, neon_shp)

    vals <- terra::values(maksed)[,1]

    mean_val <- mean(vals, na.rm = T)/100

    neon_tib <- tibble(site_code = neon_shp$site_code,
                       alpha = mean_val)

    neon_alpha <- rbind(neon_alpha, neon_tib)
}

df <- left_join(df, neon_alpha, by = 'site_code')

df_out_ <- calc_daymet_pet(df) %>%
    select(date, site_code, dayl, prcp, srad = s_rad, swe, tmax = t_max,
           tmin = t_min, vp, pet) %>%
    # srad is converted to different units in function from camels, converting back
    # to native format.
    mutate(srad = srad*11.57407)

write_feather(df_out_, glue('neon_camels_attr/data/{n}_{d}_climate_pet.feather',
                            n = network,
                            d = domain))
