sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/TE03/TE03.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/TE03/TE03.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/AB00/AB00.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/AB00/AB00.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/AT07/AT07.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/AT07/AT07.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/BC02/BC02.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/BC02/BC02.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/CP00/CP00.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/CP00/CP00.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/DV01/DV01.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/DV01/DV01.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/FK00/FK00.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/FK00/FK00.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/GV01/GV01.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/GV01/GV01.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/HO00/HO00.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/HO00/HO00.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/MC00/MC00.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/MC00/MC00.shp')->zz
mapview::mapview(zz)

sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/MC06/MC06.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/MC06/MC06.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/ON02/ON02.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/ON02/ON02.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/RG01/RG01.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/RG01/RG01.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/RN01/RN01.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/RN01/RN01.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/RS02/RS02.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/RS02/RS02.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/SM01/SM01.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/SM01/SM01.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/SM04/SM04.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/SM04/SM04.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/derived/ws_boundary__ms000/SP02/SP02.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/santa_barbara/ws_boundary__ms000/SP02/SP02.shp')->zz
mapview::mapview(zz)

sf::st_read('data/lter/plum/derived/bear_meadow/bear_meadow.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/plum/derived/ws_boundary__ms000/bear_meadow/bear_meadow.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/plum/derived/cart_creek/cart_creek.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/plum/derived/ws_boundary__ms000/cart_creek/cart_creek.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/plum/derived/saw_mill_brook/saw_mill_brook.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/plum/derived/ws_boundary__ms000/saw_mill_brook/saw_mill_brook.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/plum/derived/upper_ipswich/upper_ipswich.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/plum/derived/ws_boundary__ms000/upper_ipswich/upper_ipswich.shp')->zz
mapview::mapview(zz)

sf::st_read('data/lter/hjandrews/munged/ws_boundary__3239/GSLOOK/GSLOOK.shp')->zz
mapview::mapview(zz)
sf::st_read('data/lter/luquillo/derived/ws_boundary__ms000/QG/QG.shp')->zz
mapview::mapview(zz)


sf::st_read('data/doe/east_river/derived/wb/Avery/Avery.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/Avery/Avery.shp')->zz
mapview::mapview(zz)

sf::st_read('data/doe/east_river/derived/wb/Avery/Avery.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/Avery/Avery.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/wb/Benthette/Benthette.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/Benthette/Benthette.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/wb/Bradley/Bradley.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/Bradley/Bradley.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/wb/Copper/Copper.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/Copper/Copper.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/wb/EAQ/EAQ.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/EAQ/EAQ.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/wb/EBC/EBC.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/EBC/EBC.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/Gothic/Gothic.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/wb/Gothic/Gothic.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/Marmot/Marmot.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/wb/Marmot/Marmot.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/wb/OBJ/OBJ.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/OBJ/OBJ.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/wb/PH/PH.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/PH/PH.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/wb/Quigley/Quigley.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/Quigley/Quigley.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/wb/Rock/Rock.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/Rock/Rock.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/wb/Rustlers/Rustlers.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/Rustlers/Rustlers.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/wb/WG/WG.shp')->zz
mapview::mapview(zz)
sf::st_read('data/doe/east_river/derived/ws_boundary__ms000/WG/WG.shp')->zz
mapview::mapview(zz)

sf::st_read('data/czo/boulder/derived/ws_boundary__ms000/GGL/GGL.shp')->zz
mapview::mapview(zz)
sf::st_read('data/czo/boulder/derived/ws_boundary__ms000/GGU/GGU.shp')->zz
mapview::mapview(zz)
sf::st_read('data/czo/boulder/derived/ws_boundary__ms000/BC_SW_4/BC_SW_4.shp')->zz
mapview::mapview(zz)
sf::st_read('data/czo/boulder/derived/ws_boundary__ms000/BC_SW_20/BC_SW_20.shp')->zz
mapview::mapview(zz)


sf::st_read('~/git/macrosheds/data_acquisition/data/lter/arctic/derived/ws_boundary__ms000/Trevor_Creek_Main/Trevor_Creek_Main.shp')->zz
mapview::mapview(zz)
zz2=zz
sf::st_read('~/git/macrosheds/data_acquisition/data/lter/bonanza/derived/ws_boundary__ms000/C2/C2.shp')->zz
mapview::mapview(zz)
sf::st_read('~/git/macrosheds/data_acquisition/data/lter/luquillo//derived/ws_boundary__ms000/RI/RI.shp')->zz
mapview::mapview(zz)
